// Custom code (not generated by Stainless). See CONTRIBUTING.md.
//
// "Operations" tools: one MCP tool per Mux API operation, each with its own description, input
// schema and explicit MCP annotations. These are opt-in (`--tools=operations` or `?tools=operations`)
// and complement the default code-mode tools (`execute` + `search_docs`). They exist for MCP clients
// and directories (e.g. OpenAI's) that require every model-callable operation to be exposed upfront.

import type Mux from '@mux/ts';
import type { Tool, ToolAnnotations } from '@modelcontextprotocol/sdk/types.js';
import type { SdkMethod } from '../methods';
import {
  McpRequestContext,
  McpTool,
  Metadata,
  ToolCallResult,
  asErrorResult,
  asTextContentResult,
} from '../types';
import { operationToolDefinitions } from './operation-tool-definitions';

export type OperationToolAnnotations = Required<
  Pick<ToolAnnotations, 'readOnlyHint' | 'destructiveHint' | 'idempotentHint' | 'openWorldHint'>
>;

export type OperationToolDefinition = {
  /** MCP tool name. Matches the names Stainless used for per-endpoint tools before v13. */
  name: string;
  /** Human-readable title (OpenAPI summary). */
  title: string;
  /** Model-facing description (OpenAPI description). */
  description: string;
  /** Fully-qualified SDK method, e.g. `video.assets.list`. */
  method: string;
  httpMethod: string;
  httpPath: string;
  /** Path parameters, passed positionally to the SDK method in this order. */
  pathParams: string[];
  /** Whether the remaining arguments are passed to the SDK method as its params object. */
  hasParams: boolean;
  /** Whether the SDK method returns a page; if so the raw page body (including cursors) is returned. */
  paginated: boolean;
  inputSchema: Tool['inputSchema'];
  annotations: OperationToolAnnotations;
};

export { operationToolDefinitions };

function resolveMethod(client: Mux, method: string): (...args: unknown[]) => any {
  const parts = method.split('.');
  let target: any = client;
  for (const part of parts.slice(0, -1)) {
    target = target?.[part];
  }
  const fn = target?.[parts[parts.length - 1]!];
  if (typeof fn !== 'function') {
    throw new Error(`SDK method client.${method} is not available`);
  }
  return fn.bind(target);
}

export function operationTool(def: OperationToolDefinition): McpTool {
  const metadata: Metadata = {
    resource: def.method.split('.').slice(0, -1).join('.'),
    operation: def.annotations.readOnlyHint ? 'read' : 'write',
    tags: [],
    httpMethod: def.httpMethod,
    httpPath: def.httpPath,
  };

  const tool: Tool = {
    name: def.name,
    title: def.title,
    description: def.description,
    inputSchema: def.inputSchema,
    annotations: { title: def.title, ...def.annotations },
  };

  const handler = async ({
    reqContext,
    args,
  }: {
    reqContext: McpRequestContext;
    args: Record<string, unknown> | undefined;
  }): Promise<ToolCallResult> => {
    const { ...params } = args ?? {};
    const positional: unknown[] = [];
    for (const name of def.pathParams) {
      const value = params[name];
      if (typeof value !== 'string' || value.length === 0) {
        return {
          content: [{ type: 'text', text: `Missing required parameter: ${name}` }],
          isError: true,
        };
      }
      positional.push(value);
      delete params[name];
    }
    if (def.hasParams) {
      positional.push(params);
    }

    try {
      const fn = resolveMethod(reqContext.client, def.method);
      const promise = fn(...positional);
      if (def.paginated) {
        const response: Response = await promise.asResponse();
        return asTextContentResult(await response.json());
      }
      const result = await promise;
      if (result === undefined || result === null || result === '') {
        return asTextContentResult({ success: true });
      }
      return asTextContentResult(result);
    } catch (error) {
      // Surface API errors (e.g. 4xx validation errors) to the model as a tool error result.
      return asErrorResult(error instanceof Error ? error.message : String(error));
    }
  };

  return { metadata, tool, handler };
}

/**
 * Builds the per-operation tools.
 *
 * @param names - If provided, only tools with these names are returned.
 * @param blockedMethods - SDK methods blocked by the server's code permissions
 * (`--code-allow-http-gets`, `--code-allowed-methods`, `--code-blocked-methods`); tools for these
 * methods are omitted so both tool styles honor the same permissions.
 */
export function operationTools({
  names,
  blockedMethods,
}: {
  names?: string[] | undefined;
  blockedMethods?: SdkMethod[] | undefined;
} = {}): McpTool[] {
  const blocked = new Set((blockedMethods ?? []).map((m) => m.fullyQualifiedName));
  return operationToolDefinitions
    .filter((def) => !blocked.has(def.method))
    .filter((def) => !names || names.includes(def.name))
    .map(operationTool);
}
